// <auto-generated />
using System;
using Elias.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elias.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240513124049_BugFixForUser")]
    partial class BugFixForUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Elias.Data.Entities.Blog.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BlogDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BlogGroup")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("BlogImage")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BlogShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogSubject")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlogGroup");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("Elias.Data.Entities.Blog.BlogComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("BlogComments");
                });

            modelBuilder.Entity("Elias.Data.Entities.Blog.BlogGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlogGroupName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BlogGroups");
                });

            modelBuilder.Entity("Elias.Data.Entities.Certificate.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateDate")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CertificateID")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CertificateImage")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CertificateName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Elias.Data.Entities.Comment.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Elias.Data.Entities.Education.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationCertificate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Since")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("Elias.Data.Entities.Experience.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ExperienceDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExperienceSubject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Elias.Data.Entities.Permission.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PermissionTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9128),
                            PermissionTitle = "صفحه ی اصلی "
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9131),
                            ParentId = 41,
                            PermissionTitle = "خروج"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9135),
                            ParentId = 41,
                            PermissionTitle = "تغییر پسورد"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9137),
                            ParentId = 41,
                            PermissionTitle = "ایجاد کاربر"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9139),
                            ParentId = 41,
                            PermissionTitle = "ویرایش کاربر"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9141),
                            ParentId = 1,
                            PermissionTitle = "گروه مهارت"
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9143),
                            ParentId = 6,
                            PermissionTitle = "ایجاد گروه مهارت"
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9145),
                            ParentId = 6,
                            PermissionTitle = "ویرایش گروه مهارت"
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9146),
                            ParentId = 1,
                            PermissionTitle = "مهارت"
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9149),
                            ParentId = 9,
                            PermissionTitle = " ایجاد مهارت"
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9151),
                            ParentId = 9,
                            PermissionTitle = "ویرایش مهارت"
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9153),
                            ParentId = 9,
                            PermissionTitle = "حذف مهارت"
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9155),
                            ParentId = 1,
                            PermissionTitle = "تحصیلات"
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9157),
                            ParentId = 13,
                            PermissionTitle = "ایجاد تحصیلات"
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9159),
                            ParentId = 13,
                            PermissionTitle = "ویرایش تحصیلات"
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9161),
                            ParentId = 13,
                            PermissionTitle = "حذف تحصیلات"
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9163),
                            ParentId = 1,
                            PermissionTitle = "تجربیات"
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9165),
                            ParentId = 17,
                            PermissionTitle = "ایجاد تجربه"
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9166),
                            ParentId = 17,
                            PermissionTitle = "ویرایش تجربه"
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9168),
                            ParentId = 17,
                            PermissionTitle = "حذف تجربه"
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9170),
                            ParentId = 1,
                            PermissionTitle = "مدارک"
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9172),
                            ParentId = 21,
                            PermissionTitle = "ایجاد مدرک"
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9174),
                            ParentId = 21,
                            PermissionTitle = "ویرایش مدرک"
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9176),
                            ParentId = 21,
                            PermissionTitle = "حذف مدرک"
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9178),
                            ParentId = 1,
                            PermissionTitle = "گروه نمونه کارها "
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9180),
                            ParentId = 25,
                            PermissionTitle = "ایجاد گروه نمونه کار"
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9182),
                            ParentId = 25,
                            PermissionTitle = "ویرایش گروه نمونه کار"
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9183),
                            ParentId = 25,
                            PermissionTitle = "حذف گروه نمونه کار"
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9185),
                            ParentId = 1,
                            PermissionTitle = "نمونه کار"
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9187),
                            ParentId = 29,
                            PermissionTitle = "ایجاد نمونه کار"
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9189),
                            ParentId = 29,
                            PermissionTitle = "ویرایش نمونه کار"
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9191),
                            ParentId = 29,
                            PermissionTitle = "حذف نمونه کار"
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9193),
                            ParentId = 1,
                            PermissionTitle = "گروه بلاگ"
                        },
                        new
                        {
                            Id = 34,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9195),
                            ParentId = 33,
                            PermissionTitle = "ایجاد گروه بلاگ"
                        },
                        new
                        {
                            Id = 35,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9197),
                            ParentId = 33,
                            PermissionTitle = "ویرایش گروه بلاگ"
                        },
                        new
                        {
                            Id = 36,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9199),
                            ParentId = 33,
                            PermissionTitle = "حذف گروه بلاگ"
                        },
                        new
                        {
                            Id = 37,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9201),
                            ParentId = 1,
                            PermissionTitle = "بلاگ"
                        },
                        new
                        {
                            Id = 38,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9203),
                            ParentId = 37,
                            PermissionTitle = "ایجاد بلاگ"
                        },
                        new
                        {
                            Id = 39,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9205),
                            ParentId = 37,
                            PermissionTitle = "ویرایش بلاگ"
                        },
                        new
                        {
                            Id = 40,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9208),
                            ParentId = 37,
                            PermissionTitle = "حذف بلاگ"
                        },
                        new
                        {
                            Id = 41,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9274),
                            ParentId = 1,
                            PermissionTitle = "کاربران"
                        },
                        new
                        {
                            Id = 42,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9277),
                            ParentId = 1,
                            PermissionTitle = "پیام های من"
                        },
                        new
                        {
                            Id = 43,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9279),
                            ParentId = 42,
                            PermissionTitle = "پاسخ پیام"
                        },
                        new
                        {
                            Id = 44,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9281),
                            ParentId = 42,
                            PermissionTitle = "حذف پیام"
                        });
                });

            modelBuilder.Entity("Elias.Data.Entities.Permission.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8957),
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8960),
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8962),
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8964),
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8966),
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8968),
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8970),
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8972),
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8974),
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8976),
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8978),
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8980),
                            PermissionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8982),
                            PermissionId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8984),
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8986),
                            PermissionId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8988),
                            PermissionId = 16,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8989),
                            PermissionId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8991),
                            PermissionId = 18,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8993),
                            PermissionId = 19,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8995),
                            PermissionId = 20,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8997),
                            PermissionId = 21,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8999),
                            PermissionId = 22,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9001),
                            PermissionId = 23,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9002),
                            PermissionId = 24,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9004),
                            PermissionId = 25,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9006),
                            PermissionId = 26,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9009),
                            PermissionId = 27,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9011),
                            PermissionId = 28,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9013),
                            PermissionId = 29,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9015),
                            PermissionId = 30,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9017),
                            PermissionId = 31,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9019),
                            PermissionId = 32,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9021),
                            PermissionId = 33,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 34,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9023),
                            PermissionId = 34,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 35,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9025),
                            PermissionId = 35,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 36,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9026),
                            PermissionId = 36,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 37,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9028),
                            PermissionId = 37,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 38,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9030),
                            PermissionId = 38,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 39,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9032),
                            PermissionId = 39,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 40,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9034),
                            PermissionId = 40,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 41,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9036),
                            PermissionId = 41,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 42,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9038),
                            PermissionId = 42,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 43,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9039),
                            PermissionId = 43,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 44,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(9041),
                            PermissionId = 44,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Elias.Data.Entities.Portfolio.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("MainPicure")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PortfolioDate")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PortfolioFamily")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PortfolioLink")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PortfolioName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("Elias.Data.Entities.Portfolio.PortfolioGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioGroups");
                });

            modelBuilder.Entity("Elias.Data.Entities.Portfolio.PortfolioImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<string>("PortfolioImageName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("PortfolioImages");
                });

            modelBuilder.Entity("Elias.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8785),
                            RoleTitle = "Admin"
                        });
                });

            modelBuilder.Entity("Elias.Data.Entities.Skills.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SkillGroupId")
                        .HasColumnType("int");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SkillValue")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillGroupId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Elias.Data.Entities.Skills.SkillGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SkillGroupName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("SkillGroups");
                });

            modelBuilder.Entity("Elias.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthDay")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Familly")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("GitHub")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedIn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MainDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainSkill")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Ostan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Resumeh")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skype")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserImage")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "خیابان امیر کبیر - امیر کبیر 9/5 - پلاک 141",
                            BirthDay = "1362/06/30",
                            City = "نیشابور",
                            CreateDate = new DateTime(2024, 5, 13, 17, 10, 44, 526, DateTimeKind.Local).AddTicks(8908),
                            Email = "elias.merati@gmail.com",
                            Familly = "مرآتی",
                            GitHub = "https://github.com/EliasMerati",
                            IsActive = true,
                            LinkedIn = "https://www.linkedin.com/in/elias-merati",
                            MainDescription = "با بیش از 5 سال تجربه در کدنویسی و توسعه ی برنامه های NET. من یک برنامه نویس هوشمند و خلاق هستم.من مسلط به زبان برنامه نویسی #C هستم و توانایی توسعه ی برنامه های تحت وب و دسکتاپ را دارم. من در ایجاد برنامه های کاربردی و کیفیت بالا تخصص دارم و توانایی مشارکت در تیم را به خوبی میدانم. همچنین من با استفاده از فریمورک های مختلفی مانند  ASP .NET MVC,ASP .NET,ASP.NET CORE, ASP.NET RAZORPAGES آشنایی کامل دارم.من متعهد به اهداف شرکت و ارا یه ی راه حل های برتر هستم.",
                            MainSkill = ".Net Developer",
                            Name = "الیاس",
                            Ostan = "خراسان رضوی",
                            Password = "20-2C-B9-62-AC-59-07-5B-96-4B-07-15-2D-23-4B-70",
                            PhoneNumber = "09223610626",
                            RoleId = 1,
                            ShortDescription = "برنامه نویس دات نت با بیش از 5 سال سابقه ی برنامه نویسی وب و دسکتاپ",
                            Skills = "C# , Asp .Net MVC , Asp .Net RazorPages , Asp .Net CoreMVC , Blazor",
                            Skype = "Elias Merati",
                            UserImage = "Null",
                            UserName = "EliasAdmin"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("Elias.Data.Entities.Blog.Blog", b =>
                {
                    b.HasOne("Elias.Data.Entities.Blog.BlogGroup", "Group")
                        .WithMany("Blogs")
                        .HasForeignKey("BlogGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Elias.Data.Entities.Blog.BlogComment", b =>
                {
                    b.HasOne("Elias.Data.Entities.Blog.Blog", "Blog")
                        .WithMany("BlogComments")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Elias.Data.Entities.Permission.Permission", b =>
                {
                    b.HasOne("Elias.Data.Entities.Permission.Permission", null)
                        .WithMany("Permissions")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Elias.Data.Entities.Permission.RolePermission", b =>
                {
                    b.HasOne("Elias.Data.Entities.Permission.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elias.Data.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Elias.Data.Entities.Portfolio.Portfolio", b =>
                {
                    b.HasOne("Elias.Data.Entities.Portfolio.PortfolioGroup", "PortfolioGroup")
                        .WithMany("Portfolios")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioGroup");
                });

            modelBuilder.Entity("Elias.Data.Entities.Portfolio.PortfolioImages", b =>
                {
                    b.HasOne("Elias.Data.Entities.Portfolio.Portfolio", "Portfolio")
                        .WithMany("PortfolioImages")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Elias.Data.Entities.Skills.Skill", b =>
                {
                    b.HasOne("Elias.Data.Entities.Skills.SkillGroup", "SkillGroup")
                        .WithMany("Skills")
                        .HasForeignKey("SkillGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillGroup");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Elias.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elias.Data.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Elias.Data.Entities.Blog.Blog", b =>
                {
                    b.Navigation("BlogComments");
                });

            modelBuilder.Entity("Elias.Data.Entities.Blog.BlogGroup", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("Elias.Data.Entities.Permission.Permission", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Elias.Data.Entities.Portfolio.Portfolio", b =>
                {
                    b.Navigation("PortfolioImages");
                });

            modelBuilder.Entity("Elias.Data.Entities.Portfolio.PortfolioGroup", b =>
                {
                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("Elias.Data.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Elias.Data.Entities.Skills.SkillGroup", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
